# Generated by Django 5.0 on 2023-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1430163393927-3dab9af7ea38?q=80&w=1470', max_length=500),
        ),
    ]
