# Generated by Django 4.2.7 on 2023-12-17 05:58

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='rating',
            field=models.FloatField(validators=[movies.models.validate_number]),
        ),
    ]
